### ISSUE TITLE
Rich Presence Doesn't stay

### ISSUE THREAD

**Issue by 200Tigersbloxed** [theLMGN/rblxRP#3]
Ok, so if I join Jailbreak, for example, the rich presence will work, but if I leave and join Natural Disaster Survival, it won't work. It'll just say Playing ROBLOX. Do I have to restart the .js file after I'm done playing a game?

**Comment by theLMGN** [comment]
@200Tigersbloxed You shouldn't need to. Have you tried waiting 30 seconds after the game ahs been open?

**Comment by 200Tigersbloxed** [comment]
Ok, thank you for your response!

**Comment by yeahidontknow** [comment]
i'm having the same issue, will it be fixed soon?

**Comment by theLMGN** [comment]
Closed due to rblxRP 2.0.0, if you're having this issue still, please create a new issue
