### ISSUE TITLE
Rich Presence not working?

### ISSUE THREAD

**Issue by GreenBean4323** [theLMGN/rblxRP#4]
I ran the file, opened up a game, and it's just using the default "Playing ROBLOX for X minutes" thing.
Is this not working anymore or something?
I'm running 2.1.1 and I joined Miners Haven. Haven't left yet since opening the game, and I started rblxRP before opening it to be sure it would work.

Edit: Decided to rejoin for testing purposes, didn't work still. Reloaded Discord too, and that didn't help.

Edit 2: Could it be because Discord Stable is signed into a different account than Discord PTB, and the account on PTB is linked to my Roblox account through verify.eryn.io ? Because I can't swap accounts on Discord Stable, I have a server that an app I run automatically joins and the server itself doesn't have an invite made until the app is run and creates a single-use invite through the server bot. Users are kicked constantly for inactivity and the only way to rejoin is to run the app and keep that account signed in on Discord Stable. Stable runs my personal account while PTB runs my online persona.

**Comment by theLMGN** [comment]
If you run the application from Command Prompt or Powershell does it
give any debug output?

**Comment by GreenBean4323** [comment]
So, just straight up joining the game returned an error, but teleporting to my private island made it detect the game. Strange.
`PS C:\Users\user\Desktop\Roblox\rblxrp-win32> ./rblxrp.exe
PS C:\Users\user\Desktop\Roblox\rblxrp-win32>
 Downloading configuration...
Downloaded configuration!
Connecting to Discord...
Connected to Discord
Updating presense
[Detect] Trying to find Roblox...
[Detect:Proc] Detecting Roblox with process method
[Detect:Proc] Detected 0 Roblox instances running
Not playing anything. Open Roblox and try it out!
Updating presense
[Detect] Trying to find Roblox...
[Detect:Proc] Detecting Roblox with process method
[Detect:Proc] Detected 0 Roblox instances running
Not playing anything. Open Roblox and try it out!
Updating presense
[Detect] Trying to find Roblox...
[Detect:Proc] Detecting Roblox with process method
[Detect:Proc] Detected 3 Roblox instances running
[Detect:Proc] Couldn't find the script URL
TypeError: scriptUrl.includes is not a function
    at procDetect (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:63:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async detectGame (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:91:21)
    at async doTheThing (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:139:19)
    at async Timeout.interval [as _onTimeout] (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:179:9)
Updating presense
[Detect] Trying to find Roblox...
[Detect:Proc] Detecting Roblox with process method
[Detect:Proc] Detected 1 Roblox instances running
[Detect:Proc] Script URL https://assetgame.roblox.com/game/PlaceLauncher.ashx?request=RequestGame&browserTrackerId=28866885267&placeId=258258996&isPlayTogetherGame=false
[Detect:Proc] Found game ID 258258996
Playing Miner's Haven New Heights  by berezaa GamesΓäó
Updating presense
[Detect] Trying to find Roblox...
[Detect:Proc] Detecting Roblox with process method
[Detect:Proc] Detected 1 Roblox instances running
[Detect:Proc] Script URL https://assetgame.roblox.com/game/PlaceLauncher.ashx?request=RequestGame&browserTrackerId=28866885267&placeId=258258996&isPlayTogetherGame=false
[Detect:Proc] Found game ID 258258996
Playing Miner's Haven New Heights  by berezaa GamesΓäó
Updating presense
[Detect] Trying to find Roblox...
[Detect:Proc] Detecting Roblox with process method`
After that last line it just repeats the last 8 lines over and over.

**Comment by theLMGN** [comment]
The last lines seems to show that the script is working fine?

However 

```[Detect:Proc] Detected 3 Roblox instances running
[Detect:Proc] Couldn't find the script URL
TypeError: scriptUrl.includes is not a function
    at procDetect (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:63:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async detectGame (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:91:21)
    at async doTheThing (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:139:19)
    at async Timeout.interval [as _onTimeout] (C:\Users\user\Desktop\Roblox\rblxrp-win32\resources\app\index.js:179:9)
```
seems to be an issue.
