### ISSUE TITLE
[Feature Request] Game Icons

### ISSUE THREAD

**Issue by GreenBean4323** [theLMGN/rblxRP#5]
If it's possible, I'd love to see the Roblox Game Icon be the `Large` image asset in the Rich Presense while the Roblox logo is the `Small` image asset.

Sorry if feature requests don't go here. Feel free to delete it if it's in the wrong place. Another repository I'm in has done feature requests like this.

**Comment by SamsonCoder** [comment]
If the Roblox game icon is in rblxRP's database, then it'll be in the `Large` image asset, but if not, it'll show the Roblox icon. The `Small` image is the rblxRP icon. So you're saying that, instead of the rblxRP icon, there should be a Roblox icon, even though the game image isn't in the database, causing twice the same icon?

**Comment by theLMGN** [comment]
@GreenBean4323 Large game icons are currently supporte for the games listed here: https://gist.github.com/theLMGN/3799b5cb7b0328be7a13860e46832b0e

**Comment by GreenBean4323** [comment]
I'm pretty sure it's possible to use Roblox's API to directly fetch the game icon for the image asset. I'm pretty sure your competition seemingly does something similar, considering it fetched an icon for a game that hasn't been updated since 2011.
Up to you though, I suppose.

**Comment by theLMGN** [comment]
@GreenBean4323 Discord only lets you upload 50 images, and they must be uploaded through the Discord website.

**Comment by SamsonCoder** [comment]
So the thing that would make most sense would be to upload _(maximum)_ 50 images of the more popular games.

**Comment by GreenBean4323** [comment]
If you use their Web API system to fetch image assets, you should be able to get every game's icon readily available... But it could only be available in testing right now to certain users? I've made bots in the past, and rich presence has it available to me when I open it.

**Comment by theLMGN** [comment]
@GreenBean4323 That'd require me using undocumented Discord APIs, which I don't want to use, and t be honest, I don't want to include my user token into rblxRP.

**Comment by GreenBean4323** [comment]
I've looked into it, and it doesn't seem to require your user token to use their Web API. Looking at the documentation and such, there's no reference to entering in your user token, but even if that were the case and the token was required, this is currently a private project. Only the developer has direct access to the API. However, if he meant including his user token in the Github releases, he could easily use a password protected file system in Windows... However for Mac, I'm unsure if there's something similar.

**Comment by theLMGN** [comment]
@GreenBean4323 Discord does not allow me to provide the Roblox game image URL as a Rich Presence image, Also, because you mentioned using some password protection system, I'd need the decryption password for that, and if the password is in the program, anyone who as access to the source code, can decrypt it.

**Comment by theLMGN** [comment]
Also, if the API endpoint for modifying rich presence assets didn't require authentication,anyone could edit **any** rich presence assets to be NSFW or NSFL content

**Comment by GreenBean4323** [comment]
Yeah, Discord doesn't allow direct interface with Roblox, same for the reverse. There are 3rd party sources normally used for developer feedback webhooks you could link through with some experimentation.

**Comment by SamsonCoder** [comment]
There's no way for a Discord Rich Presence app to use an image from another server than Discord's to then put it as a Rich Presence to Discord's server. It MUST be on Discord's server. And inside the limits. It's just not possible for now.

**Comment by GreenBean4323** [comment]
> Also, if the API endpoint for modifying rich presence assets didn't require authentication,anyone could edit **any** rich presence assets to be NSFW or NSFL content

I didn't realize this was the case, but either way, I'm certain you enter that information at Discord's developer portal, making it inaccessible to your average consumer.

**Comment by GreenBean4323** [comment]
> There's no way for a Discord Rich Presence app to use an image from another server than Discord's to then put it as a Rich Presence to Discord's server. It MUST be on Discord's server. And inside the limits. It's just not possible for now.

If that's the case, he could use a webhook to reupload every asset image to his server over the course of a few days and update them when they need updates.

**Comment by SamsonCoder** [comment]
> > There's no way for a Discord Rich Presence app to use an image from another server than Discord's to then put it as a Rich Presence to Discord's server. It MUST be on Discord's server. And inside the limits. It's just not possible for now.
> 
> If that's the case, he could use a webhook to reupload every asset image to his discord server over the course of a few days and update them when they need updates.

Again, there is a limit of 50 images and there are MILLIONS of roblox games, plus uploading them would take... I don't know, years?

**Comment by GreenBean4323** [comment]
> > > There's no way for a Discord Rich Presence app to use an image from another server than Discord's to then put it as a Rich Presence to Discord's server. It MUST be on Discord's server. And inside the limits. It's just not possible for now.
> > 
> > 
> > If that's the case, he could use a webhook to reupload every asset image to his discord server over the course of a few days and update them when they need updates.
> 
> Again, there is a limit of 50 images and there are MILLIONS of roblox games, plus uploading them would take... I don't know, years?

Does it have to be uploaded *into* the Rich Presence API? Because I'm almost certain that it can take links from anywhere inside of Discord, based on what was previously said. It has a Web API built in that should in theory be able to fetch image assets.

Perhaps it requires an extra bit of coding, but that code could likely be run on a server instead of the individual's PC.

**Comment by theLMGN** [comment]
@GreenBean4323 No. Discord only allows images that has been uploaded to the Rich Presence dashboard.

And plus, I'm not interested in running a server, managing interactions, preventing abuse and all that.

**Comment by GreenBean4323** [comment]
Perhaps it's a user trial thing then. I have no clue why I was granted access because I haven't messed with their developer portal in months and my last bot has been put out of commission due to updates to node.js.

**Comment by GreenBean4323** [comment]
Well, I suppose there's always waiting a few months to see if they fully release the functionality.
Feel free to close this again, unless you see some reason to keep it open.
Also, feel free to directly message me if you'd like to, either of you.

**Comment by rollingmoai** [comment]
> No. Discord only allows images that has been uploaded to the Rich Presence dashboard.

For reference, Discord now allows you to pass an url instead of an image key (couldn't find any documentation for that anywhere, @theLMGN How'd you know about it?).

@theLMGN also can you remove the `wontfix` label for this issue now as this feature has already been added?

**Comment by foxt** [comment]
I heard about it because it got posted in the Premid server
